### ISSUE TITLE
A Practical Guide to Applying Data-Oriented Design by Andrew Kelley

### ISSUE THREAD

**Issue by kassane** [dbartolini/data-oriented-design#26]
https://media.handmade-seattle.com/practical-data-oriented-design/

**Comment by dbartolini** [comment]
https://github.com/dbartolini/data-oriented-design/commit/2a8d9327f10308c70d5a1cf7814ac0ef46b2db6d

**Comment by kassane** [comment]
@dbartolini SYCL2024 (Zig conference):
Data-Oriented Design Revisited: Type Safety in the Zig Compiler - Matthew Lugg
https://www.youtube.com/watch?v=KOZcJwGdQok
