### ISSUE TITLE
miscategorized entries

### ISSUE THREAD

**Issue by Ziusudra** [dbartolini/data-oriented-design#27]
Both of Tony Albrecht's `Pitfalls of Object Oriented Programming` entries are `Presentations`, not Blog Posts. (His `The Latency Elephant` is correctly categorized in Blog Posts.)

**Comment by dbartolini** [comment]
Fixed in https://github.com/dbartolini/data-oriented-design/commit/e45b440bc5b27df1089c5744480c08d4a01655f6.
